# Required Parameters
$BingSearchURL = "https://www.bing.com/search?q="
$NumberOfSearches = 30
$TabLimit = 6

# Array of random search queries (150 queries)
$SearchQueries = @(
    "weather",
    "latest news",
    "stock price charts",
    "football news",
    "how to cook pasta",
    "best vacation spots",
    "movie reviews",
    "healthy recipes",
    "DIY home improvement",
    "technology trends",
    "funny cat videos",
    "book recommendations",
    "fitness tips",
    "travel destinations",
    "celebrity gossip",
    "product reviews",
    "career advice",
    "home decor ideas",
    "car maintenance tips",
    "music concerts near me",
    "artificial intelligence",
    "dog training techniques",
    "financial planning",
    "gardening tips",
    "famous historical events",
    "yoga for beginners",
    "BTC price",
    "ETH price",
    "LTC price",
    "BTC dominance rate",
    "crypto news",
    "healthy breakfast recipes",
    "latest fashion trends",
    "travel hacks",
    "popular podcasts",
    "mindfulness techniques",
    "movie trailers",
    "effective study methods",
    "best budget smartphones",
    "top-rated restaurants",
    "home workout routines",
    "upcoming concerts",
    "coding tutorials",
    "photography tips",
    "self-improvement books",
    "DIY skincare remedies",
    "investment strategies",
    "vegetarian dinner recipes",
    "brain teaser puzzles",
    "home organization tips",
    "relationship advice",
    "foreign language learning",
    "DIY painting techniques",
    "travel bucket list",
    "celebrity interviews",
    "new video game releases",
    "interior design inspiration",
    "budget travel destinations",
    "popular fitness apps",
    "hiking trails near me",
    "financial literacy resources",
    "easy dessert recipes",
    "best time management techniques",
    "houseplant care tips",
    "painting techniques for beginners",
    "classic movie recommendations",
    "healthy lunch ideas",
    "latest technology gadgets",
    "best TV shows of all time",
    "time-saving hacks",
    "DIY woodworking projects",
    "famous art masterpieces",
    "effective communication skills",
    "popular social media platforms",
    "home renovation ideas",
    "best online learning platforms",
    "mindful meditation techniques",
    "home office organization",
    "top travel destinations in Europe",
    "beginner's guide to coding",
    "delicious smoothie recipes",
    "iconic fashion designers",
    "strategies for stress management",
    "outdoor camping essentials",
    "inspirational quotes",
    "famous architecture landmarks",
    "improving public speaking",
    "DIY home decor on a budget",
    "exploring national parks",
    "historical mysteries",
    "creative writing prompts",
    "benefits of regular exercise",
    "learning a musical instrument",
    "science fiction book recommendations",
    "best hiking gear",
    "mindful eating practices",
    "world's most famous landmarks",
    "beginner's guide to photography",
    "homemade skincare recipes",
    "effective time management",
    "gardening for beginners",
    "improving interpersonal skills",
    "essential kitchen gadgets",
    "must-visit museums",
    "personal finance tips",
    "DIY craft projects",
    "popular podcast genres",
    "healthy dinner ideas",
    "latest smartphone reviews",
    "classic literature books",
    "beginner's guide to painting",
    "tips for remote work productivity",
    "exploring underwater world",
    "famous historical figures",
    "essential hiking tips",
    "mindfulness in daily life",
    "home energy-saving techniques",
    "best language learning resources",
    "outdoor photography tips",
    "mindful relaxation techniques",
    "DIY home repairs",
    "world's beautiful beaches",
    "ancient civilizations mysteries",
    "exploring space discoveries",
    "simple yoga routines",
    "classic music compositions",
    "effective study environment",
    "home gardening essentials",
    "exploring different cuisines",
    "historical events that changed the world",
    "beginner's guide to drawing",
    "improving digital security",
    "creative writing strategies",
    "self-care practices",
    "essential travel accessories",
    "popular board games",
    "benefits of reading books",
    "exploring cultural festivals",
    "effective problem-solving techniques",
    "home workout equipment",
    "latest fashion collections",
    "beginner's guide to cooking",
    "tips for online shopping",
    "world's wonders of nature",
    "mindfulness exercises",
    "DIY home organization",
    "famous movie directors",
	"The dark knight",
    "War news",
    "Energy prices analysis"
)

# Shuffle the search queries
$ShuffledQueries = $SearchQueries | Get-Random -Count $NumberOfSearches

# Perform the searches
for ($i = 0; $i -lt $NumberOfSearches; $i++) {
    $SearchQuery = $ShuffledQueries[$i]
    $SearchURL = $BingSearchURL + [Uri]::EscapeDataString($SearchQuery)
    $DelaySeconds = Get-Random -Minimum 3 -Maximum 6

    # Output progress information
    Write-Host ("Search number $($i + 1) | Executing in $($DelaySeconds) seconds...") -ForegroundColor Cyan
    Start-Sleep -Seconds $DelaySeconds

    # Open the search URL in the default browser
    Start-Process $SearchURL

    if ($i % $TabLimit -eq ($TabLimit - 1)) {
        # Close the Microsoft Edge browser
        Stop-Process -Name "msedge" -Force
        Start-Sleep -Seconds 3

        # Restart Microsoft Edge browser
        Start-Process msedge
        Start-Sleep -Seconds 5
    }
}
